let cricketCaptain = [
  // source for country and captain: https://en.wikipedia.org/wiki/Captain_(cricket)
  // source for icc ranking: https://www.icc-cricket.com/rankings/mens/team-rankings/test

  {
    country: "Bangladesh",
    testCaptain: "Shakib Al Hasan",
    odiCaptain: "Tamim Iqbal",
    t20Captain: "Shakib Al Hasan",
    iccTestRank: 9,
    iccOdiRank: 7,
    iccT20Rank: 9,
  },
  {
    country: "Australia",
    testCaptain: "Pat Cummins",
    odiCaptain: "Aaron Finch",
    t20Captain: "Aaron Finch",
    iccTestRank: 1,
    iccOdiRank: 5,
    iccT20Rank: 6,
  },
  {
    country: "Afghanistan",
    testCaptain: "Hashmatullah Shahidi",
    odiCaptain: "Hashmatullah Shahidi",
    t20Captain: "Mohammad Nabi",
    iccTestRank: 20,
    iccOdiRank: 10,
    iccT20Rank: 10,
  },
  {
    country: "England",
    testCaptain: "Heather Knight",
    odiCaptain: "Heather Knight",
    t20Captain: "Heather Knight",
    iccTestRank: 4,
    iccOdiRank: 2,
    iccT20Rank: 3,
  },
  {
    country: "India",
    testCaptain: "Harmanpreet Kaur",
    odiCaptain: "Harmanpreet Kaur",
    t20Captain: "Harmanpreet Kaur",
    iccTestRank: 2,
    iccOdiRank: 3,
    iccT20Rank: 3,
  },
  {
    country: "Ireland",
    testCaptain: "Laura Delany",
    odiCaptain: "Laura Delany",
    t20Captain: "Laura Delany",
    iccTestRank: 18,
    iccOdiRank: 11,
    iccT20Rank: 12,
  },
  {
    country: "New Zealand",
    testCaptain: "Sophie Devine",
    odiCaptain: "Sophie Devine",
    t20Captain: "Sophie Devine",
    iccTestRank: 5,
    iccOdiRank: 1,
    iccT20Rank: 5,
  },
  {
    country: "Pakistan",
    testCaptain: "Bismah Maroof",
    odiCaptain: "Bismah Maroof",
    t20Captain: "Bismah Maroof",
    iccTestRank: 6,
    iccOdiRank: 5,
    iccT20Rank: 2,
  },
  {
    country: "South Africa",
    testCaptain: "Suné Luus",
    odiCaptain: "Suné Luus",
    t20Captain: "Suné Luus",
    iccTestRank: 3,
    iccOdiRank: 6,
    iccT20Rank: 4,
  },
  {
    country: "Sri Lanka",
    testCaptain: "Chamari Athapaththu",
    odiCaptain: "Chamari Athapaththu",
    t20Captain: "Chamari Athapaththu",
    iccTestRank: 7,
    iccOdiRank: 8,
    iccT20Rank: 8,
  },
  {
    country: "West Indies",
    testCaptain: "Stafanie Taylor",
    odiCaptain: "Stafanie Taylor",
    t20Captain: "Stafanie Taylor",
    iccTestRank: 8,
    iccOdiRank: 9,
    iccT20Rank: 7,
  },
  {
    country: "Zimbabwe",
    testCaptain: "Mary-Anne Musonda",
    odiCaptain: "Mary-Anne Musonda",
    t20Captain: "Mary-Anne Musonda",
    iccTestRank: 10,
    iccOdiRank: 13,
    iccT20Rank: 11,
  },
];

export { cricketCaptain };
